### ISSUE TITLE
Split documentation and binary packages

### ISSUE THREAD

**Issue by nkadel** [iusrepo/git216#12]
The documentation for git is published separately at the upstream repository. The compilation will be *much* fasterif the "git2u" packages and the "git2u-doc" packages re published distinctly, built from the distinct upstream published tarballs. There is little reason to rebuild and repackage all the documentation, and it makes backporting to older and older versions of RHEL or CentOS that much more difficult.

**Comment by carlwgeorge** [comment]
I agree, in the modern age packaging up documentation never made much sense to me anyways.  How is Fedora handling it these days?  If we go the route of a new package (see https://github.com/iuscommunity-pkg/git2u/issues/11#issuecomment-489677374) then it would be nice if we can just inherent the same setup that Fedora uses, or even toggle a macro if possible.

**Comment by evitalis** [comment]
Quick review looks like the current Fedora spec file does appear to break out the docs into their own package.

**Comment by carlwgeorge** [comment]
Since this package will be [retired soon](https://github.com/iusrepo/announce/issues/19), I'm closing this issue out.

Similar to current Fedora packages, the IUS git222 and git224 source rpms can be rebuilt with the flag `--without docs` to speed up the build if that is desired.  IUS already builds both of those packages for EL6 and EL7.
